### ISSUE TITLE
[Java 10] Illegal reflective access operation

### ISSUE THREAD

**Issue by c7hm4r** [kamax-matrix/mxisd#148]
I get this error when MXISD starts:

```
An illegal reflective access operation has occurred
Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/usr/lib/mxisd/mxisd.jar) to constructor sun.nio.ch.EPollSelectorProvider()
Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
Use --illegal-access=warn to enable warnings of further illegal reflective access operations
All illegal access operations will be denied in a future release
```

OS: Ubuntu 18.04
MXISD version: 1.3.1

full log:
```
Mär 24 22:35:44 host mxisd[741]: [main] INFO App - ------------- mxisd starting -------------
Mär 24 22:35:44 host mxisd[741]: [main] INFO io.kamax.mxisd.config.YamlConfigLoader - Reading config from /etc/mxisd/mxisd.yaml
Mär 24 22:35:48 host mxisd[741]: [main] INFO io.kamax.mxisd.config.YamlConfigLoader - Loaded config from /etc/mxisd/mxisd.yaml
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.DirectoryConfig - --- Directory config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.DirectoryConfig - Exclude:
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.DirectoryConfig -   Homeserver: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.DirectoryConfig -   3PID: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.FirebaseConfig - --- Firebase configuration ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.FirebaseConfig - Enabled: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.InvitationConfig - --- Invite config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.InvitationConfig - Resolution: {"recursive":true,"timer":1}
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - --- Generic LDAP Config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - Enabled: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.RecursiveLookupBridgeConfig - --- Bridge integration lookups config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.RecursiveLookupBridgeConfig - Enabled: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.MatrixConfig - --- Matrix config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.MatrixConfig - Domain: host.domain
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.MatrixConfig - Identity:
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.MatrixConfig -         Servers: {"matrix-org":["https://matrix.org"]}
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - --- NetIQ eDirectory Config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - Enabled: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig - --- Notification config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig - Handlers:
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig -   msisdn: raw
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig -   email: raw
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.rest.RestBackendConfig - --- REST backend config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.rest.RestBackendConfig - Enabled: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.SessionConfig - --- Session config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.SessionConfig - Global Policy: {"validation":{"enabled":true},"unbind":{"fraudulent":{"send_warning":true}}}
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ServerConfig - --- Server config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ServerConfig - Name: matrix.host.domain
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ServerConfig - Port: 8090
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ServerConfig - Public URL: https://matrix.host.domain
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - --- Synapse SQL Provider config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Enabled: true
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Type: postgresql
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Has connection info? true
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Auth enabled: false
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Directory queries: {"name":{"type":"SELECT 1"},"threepid":{"type":"SELECT 1"}}
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Identity type: mxid
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - 3PID mapping query: SELECT user_id AS uid FROM user_threepids WHERE medium = ? AND address = ?
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Identity medium queries: {}
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Profile:
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig -         Enabled: true
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig -         Display name query: SELECT displayname FROM profiles WHERE user_id = ?
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig -         Profile 3PID query: SELECT medium, address FROM user_threepids WHERE user_id = ?
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ViewConfig - --- View config ---
Mär 24 22:35:49 host mxisd[741]: [main] INFO io.kamax.mxisd.config.ViewConfig - Session: {"local":{"on_token_submit":{}},"on_token_submit":{"failure":"classpath:/templates/session/tokenSubmitFailu
Mär 24 22:35:54 host mxisd[741]: [main] INFO com.j256.ormlite.table.TableUtils - creating table 'invite_3pid'
Mär 24 22:35:55 host mxisd[741]: [main] INFO com.j256.ormlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `invite_3pid` (`id` VARCHAR , `token` VA
Mär 24 22:35:55 host mxisd[741]: [main] INFO com.j256.ormlite.table.TableUtils - creating table 'session_3pid'
Mär 24 22:35:55 host mxisd[741]: [main] INFO com.j256.ormlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `session_3pid` (`id` VARCHAR , `creation
Mär 24 22:35:55 host mxisd[741]: [main] INFO com.j256.ormlite.table.TableUtils - creating table 'as_txn'
Mär 24 22:35:55 host mxisd[741]: [main] INFO com.j256.ormlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `as_txn` (`transactionId` VARCHAR , `loc
Mär 24 22:35:56 host mxisd[741]: [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
Mär 24 22:35:56 host mxisd[741]: [main] INFO com.mchange.v2.uid.UidUtils - Failed to get local InetAddress for VMID. This is unlikely to matter. At all. We'll add some extra randomness
Mär 24 22:35:56 host mxisd[741]: java.net.UnknownHostException: host: host: Name or service not known
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1633)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.uid.UidUtils.generateVmId(UidUtils.java:70)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.uid.UidUtils.<clinit>(UidUtils.java:54)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.c3p0.impl.C3P0ImplUtils.<clinit>(C3P0ImplUtils.java:126)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<init>(PoolBackedDataSourceBase.java:288)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.<init>(AbstractPoolBackedDataSource.java:74)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:142)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.c3p0.AbstractComboPooledDataSource.<init>(AbstractComboPooledDataSource.java:138)
Mär 24 22:35:56 host mxisd[741]:         at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:47)
Mär 24 22:35:56 host mxisd[741]:         at io.kamax.mxisd.backend.sql.SqlConnectionPool.<init>(SqlConnectionPool.java:42)
Mär 24 22:35:56 host mxisd[741]:         at io.kamax.mxisd.backend.sql.synapse.Synapse.<init>(Synapse.java:35)
Mär 24 22:35:56 host mxisd[741]:         at io.kamax.mxisd.Mxisd.build(Mxisd.java:98)
Mär 24 22:35:56 host mxisd[741]:         at io.kamax.mxisd.Mxisd.start(Mxisd.java:167)
Mär 24 22:35:56 host mxisd[741]:         at io.kamax.mxisd.HttpMxisd.start(HttpMxisd.java:54)
Mär 24 22:35:56 host mxisd[741]:         at io.kamax.mxisd.MxisdStandaloneExec.main(MxisdStandaloneExec.java:64)
Mär 24 22:35:56 host mxisd[741]: Caused by: java.net.UnknownHostException: host: Name or service not known
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:926)
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1506)
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:845)
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1496)
Mär 24 22:35:56 host mxisd[741]:         at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1628)
Mär 24 22:35:56 host mxisd[741]:         ... 14 more
Mär 24 22:35:58 host mxisd[741]: [main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - --- E-mail Generator templates config ---
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - Invite: /usr/local/var/mxisd/mail_templates/invite-template.eml
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - Session:
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -   Validation: /usr/local/var/mxisd/mail_templates/validate-template.eml
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -   Unbind:
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -     Fraudulent: /usr/local/var/mxisd/mail_templates/unbind-fraudulent-template.eml
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - --- E-mail SMTP Connector config ---
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Host: mail.host.domain
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Port: 25
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - TLS Mode: 2
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Login: matrix-server@host.domain
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Has password: true
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - Found 3 providers
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy -   - io.kamax.mxisd.backend.sql.synapse.SynapseSqlThreePidProvider
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy -   - io.kamax.mxisd.lookup.provider.DnsLookupProvider
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy -   - io.kamax.mxisd.lookup.provider.ForwarderProvider
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - Recursive lookup enabled: true
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 127.0.0.0/8 is allowed for recursion
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 10.0.0.0/8 is allowed for recursion
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 172.16.0.0/12 is allowed for recursion
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 192.168.0.0/16 is allowed for recursion
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - ::1/128 is allowed for recursion
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.profile.ProfileManager - Profile Providers:
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.profile.ProfileManager -   - SynapseSqlProfileProvider
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.notification.NotificationManager - Found handler raw for medium email
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.notification.NotificationManager - --- Notification handler ---
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.notification.NotificationManager -         Handler for email: raw
Mär 24 22:35:59 host mxisd[741]: [main] INFO io.kamax.mxisd.invitation.InvitationManager - Loading saved invites
Mär 24 22:36:00 host mxisd[741]: [main] INFO io.kamax.mxisd.invitation.InvitationManager - Setting up invitation mapping refresh timer
Mär 24 22:36:00 host mxisd[741]: [main] INFO io.kamax.mxisd.directory.DirectoryManager - Directory providers:
Mär 24 22:36:00 host mxisd[741]: [main] INFO io.kamax.mxisd.directory.DirectoryManager -   - io.kamax.mxisd.backend.sql.synapse.SynapseSqlDirectoryProvider
Mär 24 22:36:00 host mxisd[741]: Mar 24, 2019 10:36:00 PM org.xnio.Xnio <clinit>
Mär 24 22:36:00 host mxisd[741]: INFO: XNIO version 3.3.8.Final
Mär 24 22:36:01 host mxisd[741]: Mar 24, 2019 10:36:01 PM org.xnio.nio.NioXnio <clinit>
Mär 24 22:36:01 host mxisd[741]: INFO: XNIO NIO Implementation Version 3.3.8.Final
Mär 24 22:36:01 host mxisd[741]: WARNING: An illegal reflective access operation has occurred
Mär 24 22:36:01 host mxisd[741]: WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/usr/lib/mxisd/mxisd.jar) to constructor sun.nio.ch.EPollSelectorProvider()
Mär 24 22:36:01 host mxisd[741]: WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
Mär 24 22:36:01 host mxisd[741]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Mär 24 22:36:01 host mxisd[741]: WARNING: All illegal access operations will be denied in a future release
Mär 24 22:36:01 host mxisd[741]: [main] INFO App - ------------- mxisd started -------------
```

**Comment by maxidorius** [comment]
Which version of Java are you running?

**Comment by c7hm4r** [comment]
```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

**Comment by maxidorius** [comment]
This is expected then - Java 8 is the primary supported JRE.
As those are only warnings, it's also fine as it is for now.
