### ISSUE TITLE
Can't invite user - InvitationManager - Answer body: {"errcode":"M_UNKNOWN","error":"Internal server error"}

### ISSUE THREAD

**Issue by Takalele** [kamax-matrix/mxisd#170]
Hi,

Cant invite users to Rooms, but direct chats invites are still working any ideas?
i attached the configs and logs below this time more readable.

Thank you in advance! 
regards Takalele

synapse version 0.99.3
mxisd version 3.3.8.Final

mxisd logs:
```
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO App - ------------- mxisd starting -------------
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.YamlConfigLoader - Reading config from /etc/mxisd/mxisd.yaml
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.YamlConfigLoader - Loaded config from /etc/mxisd/mxisd.yaml
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.DirectoryConfig - --- Directory config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.DirectoryConfig - Exclude:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.DirectoryConfig -   Homeserver: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.DirectoryConfig -   3PID: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.FirebaseConfig - --- Firebase configuration ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.FirebaseConfig - Enabled: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.InvitationConfig - --- Invite config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.InvitationConfig - Resolution: {"recursive":true,"timer":1}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - --- Generic LDAP Config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - Enabled: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.RecursiveLookupBridgeConfig - --- Bridge integration lookups config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.RecursiveLookupBridgeConfig - Enabled: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.MatrixConfig - --- Matrix config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.MatrixConfig - Domain: matrix.example.tld
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.MatrixConfig - Identity:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.MatrixConfig -         Servers: {"matrix-org":["https://matrix.org"]}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - --- NetIQ eDirectory Config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ldap.LdapConfig - Enabled: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig - --- Notification config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig - Handlers:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig -   email: raw
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.notification.NotificationConfig -   msisdn: raw
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.rest.RestBackendConfig - --- REST backend config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.rest.RestBackendConfig - Enabled: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.SessionConfig - --- Session config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.SessionConfig - Global Policy: {"validation":{"enabled":true},"unbind":{"fraudulent":{"send_warning":true}}}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ServerConfig - --- Server config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ServerConfig - Name: matrix.example.tld
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ServerConfig - Port: 8090
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ServerConfig - Public URL: https://matrix.example.tld
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - --- Synapse SQL Provider config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Enabled: true
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Type: sqlite
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Has connection info? true
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Auth enabled: false
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Directory queries: {"name":{"type":"SELECT 1"},"threepid":{"type":"SELECT 1"}}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Identity type: mxid
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - 3PID mapping query: SELECT user_id AS uid FROM user_threepids WHERE medium = ? AND address = ?
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Identity medium queries: {}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig - Profile:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig -         Enabled: true
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig -         Display name query: SELECT displayname FROM profiles WHERE user_id = ?
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.sql.SqlConfig -         Profile 3PID query: SELECT medium, address FROM user_threepids WHERE user_id = ?
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ViewConfig - --- View config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.ViewConfig - Session: {"local":{"on_token_submit":{}},"on_token_submit":{"failure":"classpath:/templates/session/tokenSubmitFailure.html","success":"classpath:/templates/session/tokenSubmitSuccess.html"}}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.j256.ormlite.table.TableUtils - creating table 'invite_3pid'
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.j256.ormlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `invite_3pid` (`id` VARCHAR , `token` VARCHAR NOT NULL , `sender` VARCHAR NOT NULL , `medium` VARCHAR NOT NULL , `address` VARCHAR NOT NULL , `roomId` VARCHAR NOT NULL , `properties` VARCHAR , PRIMARY KEY (`id`) )
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.j256.ormlite.table.TableUtils - creating table 'session_3pid'
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.j256.ormlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `session_3pid` (`id` VARCHAR , `creationTime` BIGINT NOT NULL , `server` VARCHAR NOT NULL , `medium` VARCHAR NOT NULL , `address` VARCHAR NOT NULL , `secret` VARCHAR NOT NULL , `attempt` INTEGER NOT NULL , `nextLink` VARCHAR , `token` VARCHAR NOT NULL , `validated` BOOLEAN , `validationTime` BIGINT , `isRemote` BOOLEAN NOT NULL , `remoteServer` VARCHAR , `remoteId` VARCHAR , `remoteSecret` VARCHAR , `remoteAttempt` INTEGER , `isRemoteValidated` BOOLEAN NOT NULL , PRIMARY KEY (`id`) )
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.j256.ormlite.table.TableUtils - creating table 'as_txn'
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.j256.ormlite.table.TableUtils - executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `as_txn` (`transactionId` VARCHAR , `localpart` VARCHAR , `timestamp` BIGINT NOT NULL , `result` VARCHAR NOT NULL , UNIQUE (`transactionId`,`localpart`) )
Apr 28 17:42:38 matrix mxisd[4958]: [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - --- E-mail Generator templates config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - Invite: Built-in (/threepids/email/invite-template.eml)
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - Session:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -   Validation: classpath:/threepids/email/validate-template.eml
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -   Unbind:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -     Fraudulent: classpath:/threepids/email/unbind-fraudulent.eml
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - --- E-mail SMTP Connector config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Host: mx01.example.tld
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Port: 25
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - TLS Mode: 1
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Login: jampin@example.tld
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.EmailSmtpConfig - Has password: true
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - --- SMS Generator templates config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - Invite: Built-in (/threepids/sms/invite-template.txt)
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig - Session:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -   Validation: classpath:/threepids/sms/validate-template.txt
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -   Unbind:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.medium.EmailTemplateConfig -     Fraudulent: classpath:/threepids/sms/unbind-fraudulent.txt
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.PhoneTwilioConfig - --- Phone SMS Twilio connector config ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.PhoneTwilioConfig - Account SID: myAccountSid
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.config.threepid.connector.PhoneTwilioConfig - Sender number: +123456789
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.threepid.connector.phone.PhoneSmsTwilioConnector - Twilio API has been initiated
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - Found 3 providers
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy -   - io.kamax.mxisd.backend.sql.synapse.SynapseSqlThreePidProvider
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy -   - io.kamax.mxisd.lookup.provider.DnsLookupProvider
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy -   - io.kamax.mxisd.lookup.provider.ForwarderProvider
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - Recursive lookup enabled: true
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 127.0.0.0/8 is allowed for recursion
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 10.0.0.0/8 is allowed for recursion
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 172.16.0.0/12 is allowed for recursion
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - 192.168.0.0/16 is allowed for recursion
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - ::1/128 is allowed for recursion
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.lookup.strategy.RecursivePriorityLookupStrategy - fe80::/64 is allowed for recursion
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.profile.ProfileManager - Profile Providers:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.profile.ProfileManager -   - SynapseSqlProfileProvider
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.notification.NotificationManager - Found handler raw for medium email
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.notification.NotificationManager - Found handler raw for medium msisdn
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.notification.NotificationManager - --- Notification handler ---
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.notification.NotificationManager -         Handler for msisdn: raw
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.notification.NotificationManager -         Handler for email: raw
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.invitation.InvitationManager - Loading saved invites
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.invitation.InvitationManager - Processing invite {"id":"matrix.example.tldemailinv1@example.tld","token":"oFBXFkzfVcRkbsAzxLmGZKuaz31AG240uzaLQWIaHIh8cs3FO2IsYrGrLf4QpOb8","sender":"@user2:matrix.example.tld","medium":"email","address":"inv1@example.tld","room_id":"!WPTZQwWqldzMFwwYQM:matrix.example.tld","properties":"{\"medium\":\"email\",\"address\":\"inv1@example.tld\",\"room_id\":\"!WPTZQwWqldzMFwwYQM:matrix.example.tld\",\"room_alias\":\"\",\"room_avatar_url\":\"\",\"room_join_rules\":\"invite\",\"room_name\":\"\",\"sender\":\"@user2:matrix.example.tld\",\"sender_display_name\":\"user2\",\"sender_avatar_url\":\"None\"}"}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.invitation.InvitationManager - Processing invite {"id":"matrix.example.tldemailinv2@example.tld","token":"FHICkAKw7TOuklW3cbyagDdhBn6K691CCQQWEboZe5eCBobbcVSZXxL6pypeGahi","sender":"@user1:matrix.example.tld","medium":"email","address":"inv2@example.tld","room_id":"!PUWlspmXZqkwnGgWdm:matrix.example.tld","properties":"{\"medium\":\"email\",\"address\":\"inv2@example.tld\",\"room_id\":\"!PUWlspmXZqkwnGgWdm:matrix.example.tld\",\"room_alias\":\"\",\"room_avatar_url\":\"\",\"room_join_rules\":\"invite\",\"room_name\":\"\",\"sender\":\"@user1:matrix.example.tld\",\"sender_display_name\":\"user1\",\"sender_avatar_url\":\"mxc://matrix.example.tld/SAiVfQQYLerwwQtkZfYzIilL\"}"}
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.invitation.InvitationManager - Setting up invitation mapping refresh timer
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.directory.DirectoryManager - Directory providers:
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO io.kamax.mxisd.directory.DirectoryManager -   - io.kamax.mxisd.backend.sql.synapse.SynapseSqlDirectoryProvider
Apr 28 17:42:38 matrix mxisd[4958]: Apr 28, 2019 6:17:44 PM org.xnio.Xnio <clinit>
Apr 28 17:42:38 matrix mxisd[4958]: INFO: XNIO version 3.3.8.Final
Apr 28 17:42:38 matrix mxisd[4958]: Apr 28, 2019 6:17:44 PM org.xnio.nio.NioXnio <clinit>
Apr 28 17:42:38 matrix mxisd[4958]: INFO: XNIO NIO Implementation Version 3.3.8.Final
Apr 28 17:42:38 matrix mxisd[4958]: [main] INFO App - ------------- mxisd started -------------
Apr 28 17:42:40 matrix mxisd[4737]: [Timer-0] INFO io.kamax.mxisd.invitation.InvitationManager - Checking for existing mapping for pending invites
Apr 28 17:42:40 matrix mxisd[4737]: [Timer-0] INFO io.kamax.mxisd.invitation.InvitationManager - Processing invite @user1:example.tld:!WPTZQwWqldzMFwwYQM:example.tld:email:inv1@example.tld
Apr 28 17:42:40 matrix mxisd[4737]: [Timer-0] INFO io.kamax.mxisd.invitation.InvitationManager - Processing invite @user2:example.tld:!PUWlspmXZqkwnGgWdm:example.tld:email:inv2@example.tld
Apr 28 17:42:40 matrix mxisd[4737]: [ForkJoinPool.commonPool-worker-0] INFO io.kamax.mxisd.invitation.InvitationManager - Searching for mapping created since invite @user1:example.tld:!WPTZQwWqldzMFwwYQM:example.tld:email:inv1@example.tld was created
Apr 28 17:42:40 matrix mxisd[4737]: [ForkJoinPool.commonPool-worker-0] INFO io.kamax.mxisd.invitation.InvitationManager - No mapping for pending invite @user1:example.tld:!WPTZQwWqldzMFwwYQM:example.tld:email:inv1@example.tld
Apr 28 17:42:40 matrix mxisd[4737]: [ForkJoinPool.commonPool-worker-0] INFO io.kamax.mxisd.invitation.InvitationManager - Searching for mapping created since invite @user2:example.tld:!PUWlspmXZqkwnGgWdm:example.tld:email:inv2@example.tld was created
Apr 28 17:42:40 matrix mxisd[4737]: [ForkJoinPool.commonPool-worker-0] INFO io.kamax.mxisd.invitation.InvitationManager - Found mapping for pending invite @user2:example.tld:!PUWlspmXZqkwnGgWdm:example.tld:email:inv2@example.tld
Apr 28 17:42:40 matrix mxisd[4737]: [ForkJoinPool.commonPool-worker-0] INFO io.kamax.mxisd.invitation.InvitationManager - Discovering HS for domain example.tld
Apr 28 17:42:40 matrix mxisd[4737]: [ForkJoinPool.commonPool-worker-0] INFO io.kamax.mxisd.invitation.InvitationManager - Found DNS overwrite for example.tld to https://10.255.136.20:8448
Apr 28 17:42:40 matrix mxisd[4737]: [Thread-18] INFO io.kamax.mxisd.invitation.InvitationManager - Posting onBind event to https://10.255.136.20:8448/_matrix/federation/v1/3pid/onbind
Apr 28 17:42:40 matrix mxisd[4737]: [Thread-18] INFO io.kamax.mxisd.invitation.InvitationManager - Answer code: 500
Apr 28 17:42:40 matrix mxisd[4737]: [Thread-18] WARN io.kamax.mxisd.invitation.InvitationManager - Answer body: {"errcode":"M_UNKNOWN","error":"Internal server error"}
 ```
synapse logs
```
Apr 28 17:42:40 matrix python[4500]: 2019-04-28 17:42:40,048 - synapse.http.server - 112 - ERROR - POST-269- Failed handle request via 'On3pidBindServlet': <SynapseRequest at 0x7fc66d37a400 method='POST' uri='/_matrix/federation/v1/3pid/onbind' clientproto='HTTP/1.1' site=8448>
Apr 28 17:42:40 matrix python[4500]: Traceback (most recent call last):
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
Apr 28 17:42:40 matrix python[4500]:     yield h(self, request)
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
Apr 28 17:42:40 matrix python[4500]:     callback_return = yield callback(request, **kwargs)
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/transport/server.py", line 293, in new_func
Apr 28 17:42:40 matrix python[4500]:     origin, content, request.args, *args, **kwargs
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Apr 28 17:42:40 matrix python[4500]:     result = result.throwExceptionIntoGenerator(g)
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Apr 28 17:42:40 matrix python[4500]:     return g.throw(self.type, self.value, self.tb)
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/transport/server.py", line 641, in on_POST
Apr 28 17:42:40 matrix python[4500]:     raise last_exception
Apr 28 17:42:40 matrix python[4500]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/transport/server.py", line 636, in on_POST
Apr 28 17:42:40 matrix python[4500]:     invite["signed"],
Apr 28 17:42:40 matrix python[4500]: RuntimeError: Failed to send to any server.
```
homeserver.yaml:
```
## Server ##

#
# This is set in /etc/matrix-synapse/conf.d/server_name.yaml for Debian installations.
# server_name: "SERVERNAME"

pid_file: "/var/run/matrix-synapse.pid"
public_baseurl: https://matrix.example.tld/

listeners:
  - port: 8448
    type: http
    tls: true
    bind_addresses:
      - '127.0.0.1'
      - '10.255.136.20'
    resources:
      - names: [federation]
  - port: 8008
    tls: false
    bind_addresses: ['127.0.0.1', '10.255.136.20']
    type: http
    x_forwarded: true
    resources:
      - names: [client]
        compress: true
admin_contact: 'mailto:admin@example.tld'

tls_certificate_path: "/etc/ssl/matrix.example.tld/fullchain.pem"
tls_private_key_path: "/etc/ssl/matrix.example.tld/privkey.pem"

acme:

database:
  name: "sqlite3"
  args:
    database: "/var/lib/matrix-synapse/homeserver.db"

log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: "/var/lib/matrix-synapse/media"
uploads_path: "/var/lib/matrix-synapse/uploads"

max_upload_size: 500M
max_image_pixels: 32M
dynamic_thumbnails: true
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '192.168.0.0/16'

max_spider_size: 100M

turn_uris: [ "turn:turn.example.tld:3478?transport=udp", "turn:turn.example.tld:3478?transport=tcp" ]
turn_shared_secret: "xyz"
turn_user_lifetime: 86400000

enable_registration: true
registrations_require_3pid:
  - email
registration_shared_secret: "xyz"
allow_guest_access: false

default_identity_server: https://matrix.example.tld
trusted_third_party_id_servers:
  - matrix.example.tld

signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"

password_config:

email:
   enable_notifs: false
   smtp_host: "localhost"
   smtp_port: 25
   smtp_user: "exampleusername"
   smtp_pass: "examplepassword"
   require_transport_security: False
   notif_from: "Your Friendly %(app)s Home Server <noreply@example.com>"
   app_name: Matrix
   notif_template_html: notif_mail.html
   notif_template_text: notif_mail.txt
   notif_for_new_users: True
   riot_base_url: "https://riot.example.tld"


push:
  include_content: true

user_directory:
  enabled: true
  search_all_users: false
```
mxisd.yaml
```
#######################
# Matrix config items #
#######################

matrix:
  domain: 'matrix.example.tld'


################
# Signing keys #
################

key:
  path: '/var/lib/mxisd/keys'


# Path to the SQLite DB file for mxisd internal storage
# /!\ THIS MUST **NOT** BE YOUR HOMESERVER DATABASE /!\

storage:
  provider:
    sqlite:
      database: '/var/lib/mxisd/mxisd.db'


###################
# Identity Stores #
###################

synapseSql:
  enabled: true
  type: sqlite
  connection: /var/lib/matrix-synapse/homeserver.db


#### E-mail connector
threepid:
  medium:
    email:
      identity:
        from: 'identity@example.tld'
        name: 'My Identity Server'
      connectors:
        smtp:
           host: 'mx01.example.tld'
           port: 25
           tls: 1
           login: 'jampin@example.tld'
           password: 'xyz'
           generator: 'template'
    msisdn:
      connectors:
        twilio:
           account_sid: 'myAccountSid'
           auth_token: 'myAuthToken'
           number: '+123456789'
      generator: 'template'
dns:
  overwrite:
    homeserver:
      client:
        - name: 'matrix.example.tld'
          value: 'http://10.255.136.20:8008'
      federation:
        - name: 'matrix.example.tld'
          value: 'https://10.255.136.20:8448'

notification:
  handler:
    email: 'raw'
    msisdn: 'raw'

invite:
  policy:
    ifSender:
      hasRole:
        - 'Administrator'
        - 'Moderator'
```

reverse proxy:

```
server {
       listen 80;
       server_name matrix.example.tld;
       return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name matrix.example.tld;

    ssl_certificate /etc/letsencrypt/live/matrix.example.tld/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matrix.example.tld/privkey.pem;

    # If you don't wanna serve a site, comment this out
    root /var/www/html;
    index index.html index.htm;
    client_max_body_size 1024M;

   location ^/_matrix/client/r0/register/[^/]/?$ {
        proxy_pass              http://10.255.136.20:8090;
        proxy_set_header        Host $host;
        proxy_set_header        X-Forwarded-For $remote_addr;
}

    location ~* ^/_matrix/client/r0/rooms/([^/]+)/invite$ {
    proxy_pass              http://10.255.136.20:8090;
    proxy_set_header    Host $host;
    proxy_set_header    X-Forwarded-For $remote_addr;
    }

    location /_matrix/client/r0/user_directory {
        proxy_pass http://10.255.136.20:8090/_matrix/client/r0/user_directory;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

   location /_matrix/identity {
        proxy_pass http://10.255.136.20:8090/_matrix/identity;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    location /_matrix {
      proxy_pass http://10.255.136.20:8008;
      proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

**Comment by maxidorius** [comment]
Please upgrade to [the latest version of mxisd](https://github.com/kamax-matrix/mxisd/releases/latest). Your version is too old for synapse v0.99.3
